#
# QGroundControl android build environment
#

FROM ubuntu:xenial
MAINTAINER Daniel Agar <daniel@agar.ca>

ENV QMAKESPEC=android-g++

ENV QT_PATH /opt/Qt
ENV QT_ANDROID ${QT_PATH}/5.9.2/android_armv7

ENV ANDROID_HOME /opt/android-sdk-linux

ENV ANDROID_SDK_ROOT ${ANDROID_HOME}

ENV ANDROID_NDK_ROOT /opt/android-ndk
ENV ANDROID_NDK_TOOLCHAIN_PREFIX arm-linux-androideabi
ENV ANDROID_NDK_TOOLCHAIN_VERSION 4.9
ENV ANDROID_NDK_HOST linux-x86_64
ENV ANDROID_NDK_PLATFORM android-21
ENV ANDROID_NDK_TOOLS_PREFIX ${ANDROID_NDK_TOOLCHAIN_PREFIX}

ENV TERM=xterm
ENV PATH /usr/lib/ccache:${PATH}:${QT_ANDROID}/bin:${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

RUN	dpkg --add-architecture i386 \
	&& apt-get update \
	&& DEBIAN_FRONTEND=noninteractive apt-get -y --quiet --no-install-recommends install \
		ant \
		ccache \
		default-jdk \
		git \
		gosu \
		libc6:i386 \
		libdbus-1-3 \
		libfontconfig1 \
		libice6 \
		libncurses5:i386 \
		libsm6 \
		libstdc++6:i386 \
		libxext6 \
		libxrender1 \
		libz1:i386 \
		make \
		wget \
	&& apt-get -y autoremove \
	&& apt-get clean autoclean \
	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# Download & unpack Qt 5.9 toolchains & clean
COPY scripts/extract-qt-installer.sh /tmp/extract-qt-installer.sh
RUN	wget -q "http://download.qt-project.org/official_releases/qt/5.9/5.9.2/qt-opensource-linux-x64-5.9.2.run" -O /tmp/qt-opensource-linux-x64-5.9.2.run \
	&& QT_CI_PACKAGES=qt.592.android_armv7 /tmp/extract-qt-installer.sh /tmp/qt-opensource-linux-x64-5.9.2.run "$QT_PATH" \
	&& find "$QT_PATH" -mindepth 1 -maxdepth 1 ! -name '5.*' -exec echo 'Cleaning Qt SDK: {}' \; -exec rm -r '{}' \; \
	&& rm -rf /tmp/*

# Android SDK r24
RUN	wget -q "http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz" -O /tmp/android-sdk.tgz \
	&& tar --no-same-owner -xf /tmp/android-sdk.tgz -C /opt \
	&& echo "y" | android update sdk -u -a -t tools,platform-tools,build-tools-21.1.2,$ANDROID_NDK_PLATFORM \
	&& rm -rf /tmp/*

# Android NDK r10e
RUN	wget -q "http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin" /tmp/android-ndk.bin \
	&& cd /tmp && chmod +x android-ndk.bin && ./android-ndk.bin > /dev/null && mv android-ndk-r10e $ANDROID_NDK_ROOT && chmod -R +rX $ANDROID_NDK_ROOT \
	&& rm -rf /tmp/*

# create and start as LOCAL_USER_ID
COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["/bin/bash"]
